-- COPY AND PASTE THIS ENTIRE FILE INTO SUPABASE SQL EDITOR
-- Then click RUN

ALTER TABLE gallery ADD COLUMN IF NOT EXISTS filename VARCHAR(255);
ALTER TABLE gallery ADD COLUMN IF NOT EXISTS file_path TEXT;
ALTER TABLE gallery ADD COLUMN IF NOT EXISTS file_size INTEGER;
ALTER TABLE gallery ADD COLUMN IF NOT EXISTS mime_type VARCHAR(100);
ALTER TABLE gallery ADD COLUMN IF NOT EXISTS public_url TEXT;
ALTER TABLE gallery ADD COLUMN IF NOT EXISTS alt_text VARCHAR(255);
ALTER TABLE gallery ADD COLUMN IF NOT EXISTS tags TEXT[];
ALTER TABLE gallery ADD COLUMN IF NOT EXISTS seo_title VARCHAR(255);
ALTER TABLE gallery ADD COLUMN IF NOT EXISTS seo_description TEXT;
ALTER TABLE gallery ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE gallery ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
ALTER TABLE gallery ADD COLUMN IF NOT EXISTS width INTEGER;
ALTER TABLE gallery ADD COLUMN IF NOT EXISTS height INTEGER;

CREATE INDEX IF NOT EXISTS idx_gallery_filename ON gallery(filename);
CREATE INDEX IF NOT EXISTS idx_gallery_is_active ON gallery(is_active);
CREATE INDEX IF NOT EXISTS idx_gallery_tags ON gallery USING GIN(tags);